// Document Action Types
export const DOCUMENT_GET_REQUEST = 'DOCUMENT_GET_REQUEST';
export const DOCUMENT_GET_SUCCESSFUL = 'DOCUMENT_GET_SUCCESSFUL';
export const DOCUMENT_GET_FAILED = 'DOCUMENT_GET_FAILED';
export const DOCUMENT_SAVE_REQUEST = 'DOCUMENT_SAVE_REQUEST';
export const DOCUMENT_SAVE_SUCCESSFUL = 'DOCUMENT_SAVE_SUCCESSFUL';
export const DOCUMENT_SAVE_FAILED = 'DOCUMENT_SAVE_FAILED';
export const DOCUMENTS_FETCH_REQUEST = 'DOCUMENTS_FETCH_REQUEST';
export const DOCUMENTS_FETCH_SUCCESSFUL = 'DOCUMENTS_FETCH_SUCCESSFUL';
export const DOCUMENTS_FETCH_FAILED = 'DOCUMENTS_FETCH_FAILED';

// User Action Types
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const NEW_DOCUMENT = 'NEW_DOCUMENT';
export const DOCUMENT_CANCELLED = 'DOCUMENT_CANCELLED';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESSFUL = 'FETCH_USERS_SUCCESSFUL';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const FETCH_ROLES_REQUEST = 'FETCH_ROLES_REQUEST';
export const FETCH_ROLES_SUCCESSFUL = 'FETCH_ROLES_SUCCESSFUL';
export const FETCH_ROLES_FAILED = 'FETCH_ROLES_FAILED';
